### ISSUE TITLE
Agentforce for Developers does not respond

### ISSUE THREAD

**Issue by benkean** [forcedotcom/Einstein-GPT-for-Developers#153]
### Summary

When I give Dev Assistant a prompt, it shows Thinking... and then nothing.

### Steps To Reproduce:

1.  Open WSL: Ubuntu 20.04.6 LTS (GNU/Linux 5.15.167.4-microsoft-standard-WSL2 x86_64)
2.  Navigate to sf project folder
3.  run command: code .
4. Set default org in vs code
5. open agentforce:Dev Assistant extension
6. enter a prompt like: "Hi can you help me create an Account Trigger?"

### Expected result
Dev Assistant responds with some helpful answer.

### Actual result
The  agentforce: dev assistant extension shows Thinking... and then nothing.

### Additional information

![Image](https://github.com/user-attachments/assets/6812d303-d9a6-48d8-9e0b-bc67a07def12)

**Salesforce Extension Version in VS Code**:
Salesforce Extension Pack  v63.6.0
Salesforce Extension Pack (Expanded)  v63.6.0 

**Salesforce Einstein For Developers Version in VS Code**:
Agentforce for Developers  v2.2.0 

**OS and version**:
OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
Ubuntu 20.04.6 LTS (GNU/Linux 5.15.167.4-microsoft-standard-WSL2 x86_64)

**VS Code version**:
Version: 1.98.2 (user setup)
Commit: ddc367ed5c8936efe395cffeec279b04ffd7db78
Date: 2025-03-12T13:32:45.399Z
Electron: 34.2.0
ElectronBuildId: 11161602
Chromium: 132.0.6834.196
Node.js: 20.18.2
V8: 13.2.152.36-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by mingxuanzhangsfdx** [comment]
Hi @benkean , I am curious if this happen to all orgs that are available to you. If you do not have another org, you sign up one for free with this [link](https://developer.salesforce.com/). 

Also please let me know if other features work for you such as test case generation and inline auto completion.

**Comment by mingxuanzhangsfdx** [comment]
Also, could you please provide your org id with us? So we can check the log to see what's going on. @benkean

**Comment by benkean** [comment]
@mingxuanzhangsfdx Thank you for looking into this for me.

The dev sandbox I'm using is 00DVF00000DgBFh2AN. I experience the same issue in the prod org for this sandbox, as well as in another separate prod org that I own. I am not on a VPN when testing this.

Here is a prompt where this failed: "promptId": "aa1d4502-5eb3-4f7a-b489-e8fe433b4b3e"

sendTelemetry {"commandName":"sfdx__eGPT_chat_interaction_event","commandSource":"Chat","promptId":"aa1d4502-5eb3-4f7a-b489-e8fe433b4b3e","sequenceId":"1","codeBlockQuantity":1,"streamDuration":14325.499756,"timeToFirstTokenDuration":2702.022199,"status":"success","sessionId":"2a5ad26b-8510-4e5b-bd15-9962308bf33a","questionLength":"34","generatedLinesCount":56,"generatedCharacterCount":3924,"wasOutputContextPrevented":false,"contextLanguage":"apex"}

**Comment by mingxuanzhangsfdx** [comment]
Hi @benkean , could you try to turn off RAG in your VSCode setting, reload your VSCode workspace and try? The recommended RAM is at least 8GB to use it but I could see the RAM of the VM only 3GB.

![Image](https://github.com/user-attachments/assets/f50134d7-859e-409b-9c5b-5836a9a022f4)

**Comment by benkean** [comment]
@mingxuanzhangsfdx Disabled RAG and increased memory of VM to 8GB. Still no response from the Dev Assistant. New Telemetry below.

I forgot that you asked about in-line and test generation agent. Both of these features seem to work.

```JSON
sendTelemetry {"commandName":"sfdx__eGPT_chat_interaction_event","commandSource":"Chat","promptId":"9f8dd42e-85a0-4305-9b35-18c86e5d7cc4","sequenceId":"2","codeBlockQuantity":1,"streamDuration":18141.642288,"timeToFirstTokenDuration":1565.89151,"status":"success","sessionId":"510c96c4-081c-4cc6-ac8f-223ffefd9d91","chatSlashCommandName":"document","questionLength":"99","generatedLinesCount":68,"generatedCharacterCount":5229,"wasOutputContextPrevented":false,"contextLanguage":"apex"}
```

**Comment by mingxuanzhangsfdx** [comment]
Hi @benkean ,

Please reach out to me at mingxuanzhang@salesforce.com. 

We would like to schedule some time next week to have a debugging session. Thank you!

**Comment by klewis-sfdc** [comment]
Hi Ben!  Let's try this vsix with some extra logging to see if we can gain any more info:

[salesforcedx-einstein-gpt-2.2.0-extra-dev-assistant-logging-041025.vsix.zip](https://github.com/user-attachments/files/19694273/salesforcedx-einstein-gpt-2.2.0-extra-dev-assistant-logging-041025.vsix.zip)

**Comment by klewis-sfdc** [comment]
Hi Ben, thank you for your help in trying to get to the bottom of this one yesterday.  It looks like the request is being made and the response is making it back to the extension, but there is some sort of problem when the content of the response is posted back to the UI.  I have created another custom .vsix where we've slightly modified the data structure that is sent from the extension to the UI for each part of the streamed response, passing it as a string instead of a json object.  When you have a chance, if you could install and run this .vsix, and then email us back the logs, we'll take another look and see if we can glean any new information that would help us pinpoint a root cause.  Thank you again for all of your help with this! -Ken

[salesforcedx-einstein-gpt-2.2.0-extra-dev-assistant-logging-041125.vsix.zip](https://github.com/user-attachments/files/19715344/salesforcedx-einstein-gpt-2.2.0-extra-dev-assistant-logging-041125.vsix.zip)

**Comment by bct8925** [comment]
Hi @klewis-sfdc!

I have a similar environment and issue as OP. I've installed that version of the extension, and both the Dev Assistant & Inline completions are failing. 

Dev Assistant promptId: "abbe0408-0e94-4eba-89ed-359634e5a3e7"
Dev Assistant logs:
`{"x-client-trace-id": "eGPT-trace_b98c6cfa-eaa7-4e61-96a8-e85a61929872_1047bdbf-a1d4-43b0-ab96-ff9344ca329e"}`
`responseMessage.payload.responseMessage.rawMessage: It appears the user query is missing some context or details to provide a specific response. Please provide more information about the user's question or the problem they are facing, and I will do my best to help you.`

Inline completion promptId: "12f2851e-cc33-4cc3-a29d-731a11ef0565"
Inline completion logs:
`{"x-client-trace-id": "eGPT-trace_b230b3b2-808e-4c18-b99b-402c34956b04_12f2851e-cc33-4cc3-a29d-731a11ef0565_IAC"}`
`[Extension Host] Failed to retrieve inline completions from SfAPI AxiosError: Request failed with status code 400`
`[Extension Host] InlineCompletionService.getInlineCompletions: Error requesting inline completion SFApiRequestError: [response_code: 400] Messages must be non-null and size > 0.`

**Comment by diyer** [comment]
@bct8925 the issue you are seeing should be fixed. please verify and let us know if you see any other issues.

**Comment by bct8925** [comment]
@diyer Thanks! The autocomplete is now working but I'm still not getting responses through the dev assistant, there's a "cannot read properties of undefined, reading default" exception in the console and the telemetry:
`sendTelemetry {"commandName":"sfdx__eGPT_chat_interaction_event","commandSource":"Chat","promptId":"317d06de-def1-4567-b62e-22b2c3e92595","sequenceId":"10","codeBlockQuantity":1,"streamDuration":4807.094482,"timeToFirstTokenDuration":2410.052537,"status":"success","sessionId":"e0609000-95ad-4899-8edc-92dcc525d24c","questionLength":"21","generatedLinesCount":15,"generatedCharacterCount":993,"wasOutputContextPrevented":false,"contextLanguage":"apex"}
`

**Comment by diyer** [comment]
@bct8925 , when you say you have a similar environment, are you also on Open WSL ?

**Comment by bct8925** [comment]
@diyer Yep, I've tried Ubuntu and Debian

**Comment by RitamAgrawal** [comment]
@benkean Are you still encountering the issue with latest A4D?

**Comment by benkean** [comment]
@RitamAgrawal I've updated to v2.5.0 and I still experience the same issue.
```
sendTelemetry {"commandName":"sfdx__eGPT_chat_interaction_event","commandSource":"Chat","promptId":"20a05adc-db5f-4a2f-a348-becc7d7ae228","sequenceId":"2","codeBlockQuantity":0,"streamDuration":6269.57459,"timeToFirstTokenDuration":2016.341159,"status":"success","sessionId":"d69643a0-01c7-4103-9006-a7bfeeda8ec2","questionLength":"47","generatedLinesCount":11,"generatedCharacterCount":1480,"wasOutputContextPrevented":false,"contextLanguage":"apex"}
```

![Image](https://github.com/user-attachments/assets/f5d22c0e-ff9c-4710-be71-b06d8d50e2b7)

**Comment by mingxuanzhangsfdx** [comment]
Hey @benkean , could you please try the debugging version of vsix we sent you here https://github.com/forcedotcom/Einstein-GPT-for-Developers/issues/153#issuecomment-2798248050?

**Comment by benkean** [comment]
@mingxuanzhangsfdx emailed you and Kenneth the log.

**Comment by mingxuanzhangsfdx** [comment]
Hey @benkean , thank you so much for following up with us. Could you please try the following steps - 
1. Let us know the color theme of your VSCode. You can check it out in VSCode Setting UI 
![Image](https://github.com/user-attachments/assets/00a7cfce-73a5-4787-b225-ea03e2f09e7f)
2. Unzip and install the vsix in the attachment of the comment. 
3. Send something in Dev Assistant, see if you can see an output and let us know the result, and snapshot the developer tool log as you did before.
4. Update the color theme of your VSCode to Dark (Visual Studio) or Dark + if you have not.
5. Reload VSCode, repeat step 3 and snapshot the log
6. (bonus step if you are able to see result after you change Color Theme with this debugging vsix) could you try to keep that color theme and try with our extension in release and see if everything works fine?

We appreciate your patience and cooperation with us! 

cc @bct8925 appreciate it if you can also give a try.

Please send your results again to our email

Mingxuan Zhang <mingxuanzhang@salesforce.com> and Kenneth Lewis <kenneth.lewis@salesforce.com>



 
[salesforcedx-einstein-gpt-fix-theming-050825.vsix.zip](https://github.com/user-attachments/files/20112847/salesforcedx-einstein-gpt-fix-theming-050825.vsix.zip)

**Comment by diyer** [comment]
closing this as Dev assistant is deprecated.
please use latest version of Agentforce Vibes extension and create a new issue if the problem persists. Thank you!
