### ISSUE TITLE
Agentforce : Agent : TEST CASE GENERATION DOES'T WORK

### ISSUE THREAD

**Issue by sabhowal** [forcedotcom/Einstein-GPT-for-Developers#154]
### Summary

Agentforce : Agent : TEST CASE GENERATION is throwing up an error when an APEX TEST class generation is being tried.

### Steps To Reproduce:

1. Open Agentforce : Agents extension on VS Code.
2. Select Test Type = Apex.
3. Select the respective .cls apex file
4. Click on 'Select Apex Method'.
5.  Throws up an error.

### Expected result

The prompt should display a list of available methods in the selected APEX .cls file

### Actual result

It throws a system error pop up in VS code saying "Oops! We hit a snag. Try again. If the issue persists, you can open the console by running Developer: Toggle Developer Tools for more information, or log an [issue](https://github.com/forcedotcom/Einstein-GPT-for-Developers/issues) and we’ll investigate it."

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: @salesforce/cli/2.67.7 darwin-arm64 node-v20.4.0

**Salesforce Einstein For Developers Version in VS Code**: 2.2.0

**OS and version**: maOS Sonoma, Version 14.6.1

**VS Code version**: Version: 1.98.2 (Universal)

![Image](https://github.com/user-attachments/assets/f34bd9d8-3346-44a2-8ba2-833e30062a70)

**Comment by mingxuanzhangsfdx** [comment]
Hi @sabhowal 

Can you please run the following steps to help us debug further?

1. Open the Command Palette and search for Preferences: Open Settings (UI)
2. Search for Agentforce and check off the following: Salesforce: Einstein for Developers: Enable Debug Logging. This turns on logging so we can debug further - you're free to turn this off once you've shared the following information.

![Image](https://github.com/user-attachments/assets/619ad1aa-46de-4a49-86d1-151e345f6d5e)

3. Select Help > Toggle Developer Tools

![Image](https://github.com/user-attachments/assets/99d16717-21ad-4c3f-8a9e-fb2be605b52c)

4. Now enter something and send as you did above

5. Please send us a screenshot of your output in developer tools like this

![Image](https://github.com/user-attachments/assets/caceb7c7-8952-400b-8819-0dd2ea9898b7)

**Comment by sabhowal** [comment]
Hi @mingxuanzhangsfdx 
Thanks for your reply and sorry for late in response !!
Now the issue with the TEST case generation is working fine, but once clicked on "Accept", it's throwing up some error on the console as below - 

![Image](https://github.com/user-attachments/assets/21976354-b4af-4f55-86b8-accda1aaff59)

![Image](https://github.com/user-attachments/assets/2c5934df-d527-4e0a-82ee-81206b22b17c)

It works fine till here. The error on clicking "Accept" is below - 

![Image](https://github.com/user-attachments/assets/83aa36be-f359-4f6d-9ec5-3d396724e903)

**Comment by diyer** [comment]
Thank you @sabhowal , we will look into this. Can you please tell how did you get Apex TCG to work after the initial issue?

**Comment by MounicaSaya** [comment]
Hello @sabhowal could you please let's know how the issue got fixed? I see same issue where when I try selecting test method it's showing **Oops! we hit a snag.** error.

**Comment by SeanSobey** [comment]
I fixed this my installing the JAVA runtime required by the salesforce intellisence extension:

![Image](https://github.com/user-attachments/assets/183a9c87-3b1b-48f1-ac07-237bad9c2547)

**Comment by rajdipray02** [comment]
Hi @sabhowal,
I'm still getting the below error after following the mention steps. Could you please help me to fix this issue!

<img width="902" alt="Image" src="https://github.com/user-attachments/assets/e5ab5b39-de88-4b51-bc1e-b233db17c2a8" />

**Comment by diyer** [comment]
Closing this as Dev assistant is deprecated.
please use latest version of Agentforce Vibes extension and create a new issue if the problem persists. Thank you!
